# general configuration
url: http://commonsmachinery.github.io
baseurl: '/cm-web'

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/CommonsMachinery_Logo_Vertical_LightBackground_Transparent.png"
  # author will appear under the avatar (optional)
  # author: "Compass"
  # tagline will appear under the title (optional)
  tagline: "The smurf for your smurf"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
